version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels:
      - bumpless
    ignore:
      # gdal version is dictated by https://github.com/lambgeo/docker-lambda, currently 3.8.3 
      - dependency-name: gdal[numpy]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - bumpless
