Parameters:

  EarthdataUsername:
    Type: String

  EarthdataPassword:
    Type: String
    NoEcho: true

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      Tags:
        - Key: DAR
          Value: "NO"

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: deployment_package/
      Handler: opera_rtc_s1_browse.create_browse.lambda_handler
      MemorySize: 128
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.11
      Timeout: 300
      Layers:
        - arn:aws:lambda:us-west-2:524387336408:layer:gdal38:4
      Environment:
        Variables:
          EARTHDATA_USERNAME: !Ref EarthdataUsername
          EARTHDATA_PASSWORD: !Ref EarthdataPassword
          BUCKET: !Ref Bucket
          GDAL_DATA: /opt/share/gdal
          PROJ_LIB: /opt/share/proj

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Lambda}"
      RetentionInDays: 90

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
          Effect: Allow
      Policies:
        - PolicyName: policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Sub "arn:aws:s3:::${Bucket}/*"
