name: Deploy to AWS
description: Deploy the STAC API

inputs:
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  CLOUDFORMATION_ROLE_ARN:
    required: true
  EARTHDATA_USERNAME:
    required: true
  EARTHDATA_PASSWORD:
    required: true
  STACK_NAME:
    required: true
  TEMPLATE_BUCKET:
    required: true

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt -t src/opera_rtc_s1_browse

    - shell: bash
      run: |
        aws cloudformation package \
          --template-file cloudformation.yml \
          --s3-bucket ${TEMPLATE_BUCKET} \
          --output-template-file packaged.yml
        aws cloudformation deploy \
          --stack-name ${STACK_NAME} \
          --template-file packaged.yml \
          --role-arn ${CLOUDFORMATION_ROLE_ARN} \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides \
              EarthdataUsername="${EARTHDATA_USERNAME}" \
              EarthdataPassword="${EARTHDATA_PASSWORD}"
