name: Deploy to AWS

inputs:
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  EARTHDATA_USERNAME:
    required: true
  EARTHDATA_PASSWORD:
    required: true
  VPC_ID:
    required: true
  SUBNET_IDS:
    required: true
  STACK_NAME:
    required: true
  TEMPLATE_BUCKET:
    required: true

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - shell: bash
      run: |
        ./build_deployment_package.sh
        aws cloudformation package \
          --template-file cloudformation.yml \
          --s3-bucket ${{ inputs.TEMPLATE_BUCKET }} \
          --output-template-file packaged.yml
        aws cloudformation deploy \
          --stack-name ${{ inputs.STACK_NAME }} \
          --template-file packaged.yml \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides \
              EarthdataUsername="${{ inputs.EARTHDATA_USERNAME }}" \
              EarthdataPassword="${{ inputs.EARTHDATA_PASSWORD }}" \
              VpcId="${{ inputs.VPC_ID }}" \
              SubnetIds="${{ inputs.SUBNET_IDS }}"
