name: Deploy to Earthdata Cloud UAT

on:
  push:
    branches:
      - develop

concurrency: deploy-uat

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: uat

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
          STACK_NAME: opera-rtc-s1-browse-uat
          TEMPLATE_BUCKET: cf-templates-118ylv0o6jp2n-us-west-2
